const { GoogleGenerativeAI } = require("@google/generative-ai");
async function getGuides(origin) {
  try {
    const res = await fetch(`${origin}/_data/guides.json`);
    if (!res.ok) return [];
    return await res.json();
  } catch (e) {
    return [];
  }
}

/* ===== IN-MEMORY SAFETY LAYERS ===== */

// Cache: normalized question → AI response
const RESPONSE_CACHE = new Map();

// Rate limiting: IP → { count, reset }
const RATE_LIMIT = new Map();

// Config
const CACHE_TTL_MS = 6 * 60 * 60 * 1000; // 6 hours
const RATE_LIMIT_WINDOW_MS = 10 * 60 * 1000; // 10 minutes
const RATE_LIMIT_MAX = 10; // requests per window

const AFFILIATES = {
  flights: "https://expedia.com/affiliates/expedia-home.hMJbWB1",
  hotels: "https://expedia.com/affiliate/kpS9be0",
  tours:
    "https://www.viator.com/?pid=P00218939&mcid=42383&medium=link&medium_version=selector",
  transfers: "https://kiwitaxi.tpk.mx/7OgDoKGT",
  jets: "https://www.villiersjets.com/?id=9474",
};

function normalizeQuestion(q) {
  return q.toLowerCase().trim().replace(/\s+/g, " ");
}

function getClientIP(event) {
  return (
    event.headers["x-forwarded-for"]?.split(",")[0] ||
    event.headers["client-ip"] ||
    "unknown"
  );
}

function isRateLimited(ip) {
  const now = Date.now();
  const entry = RATE_LIMIT.get(ip);

  if (!entry || now > entry.reset) {
    RATE_LIMIT.set(ip, { count: 1, reset: now + RATE_LIMIT_WINDOW_MS });
    return false;
  }

  if (entry.count >= RATE_LIMIT_MAX) return true;

  entry.count++;
  return false;
}

function getCachedResponse(key) {
  const cached = RESPONSE_CACHE.get(key);
  if (!cached) return null;

  if (Date.now() > cached.expires) {
    RESPONSE_CACHE.delete(key);
    return null;
  }

  return cached.data;
}

function setCachedResponse(key, data) {
  RESPONSE_CACHE.set(key, {
    data,
    expires: Date.now() + CACHE_TTL_MS,
  });
}

exports.handler = async function (event) {
  try {
    /* ─────────────────────────────────────────────── */
    /* 1️⃣ METHOD & INPUT VALIDATION */
    /* ─────────────────────────────────────────────── */
    if (event.httpMethod !== "POST") {
      return { statusCode: 405, body: "Method Not Allowed" };
    }

    const { question } = JSON.parse(event.body || "{}");

    if (!question || question.trim().length < 6) {
      return {
        statusCode: 400,
        body: JSON.stringify({ error: "Invalid question" }),
      };
    }

    /* ─────────────────────────────────────────────── */
    /* 🚦 RATE LIMITING */
    /* ─────────────────────────────────────────────── */

    const ip = getClientIP(event);

    if (isRateLimited(ip)) {
      return {
        statusCode: 429,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          error: "Too many requests. Please slow down and try again shortly.",
        }),
      };
    }

    /* ─────────────────────────────────────────────── */
    /* 2️⃣ ENV VARS */
    /* ─────────────────────────────────────────────── */
    const { GEMINI_API_KEY, YOUTUBE_API_KEY, YOUTUBE_CHANNEL_ID } = process.env;

    if (!GEMINI_API_KEY || !YOUTUBE_API_KEY || !YOUTUBE_CHANNEL_ID) {
      throw new Error("Missing environment variables");
    }

    /* ─────────────────────────────────────────────── */
    /* 3️⃣ GEMINI SETUP */
    /* ─────────────────────────────────────────────── */
    const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);

    const model = genAI.getGenerativeModel({
      model: "models/gemini-flash-latest",
      generationConfig: {
        temperature: 0.4,
        responseMimeType: "application/json",
      },
    });

    /* ─────────────────────────────────────────────── */
    /* 4️⃣ GUIDES (AUTO FROM ELEVENTY DATA) */
    /* ─────────────────────────────────────────────── */

    // Resolve site origin safely (Netlify-compatible)
    const origin =
      event.headers.origin ||
      event.headers.referer?.split("/").slice(0, 3).join("/") ||
      "https://paradize.life";

    // Fetch guides generated by Eleventy
    const guides = await getGuides(origin);

    // Prepare titles for the prompt
    const guideTitles = guides.length
      ? guides.map((g) => g.title).join("\n- ")
      : "";

    /* ─────────────────────────────────────────────── */
    /* 5️⃣ PROMPT */
    /* ─────────────────────────────────────────────── */
    const prompt = `
You are Paradise AI, a professional travel advisor.

STRICT RULES:
- NO nightlife, alcohol, clubs, gambling
- NO hallucination or guessing
- NO markdown
- NO emojis

CONTENT STYLE:
- Calm, expert, factual
- High-end experiences only

OUTPUT REQUIREMENTS:
- Return ONLY valid JSON
- Use clean semantic HTML (<p>, <h3>, <ul>, <li>)
- Do NOT invent URLs
- Use placeholders ONLY

AFFILIATE PLACEHOLDERS:
{{AFF_FLIGHTS}}
{{AFF_HOTELS}}
{{AFF_TOURS}}
{{AFF_TRANSFERS}}
{{AFF_JETS}}

AVAILABLE GUIDES (USE TITLES ONLY):
- ${guideTitles}

RULES FOR GUIDES:
- Recommend max 3
- If none fit, return empty array

JSON FORMAT:
{
  "video_query": "",
  "answer_html": "",
  "related_guides": [
    { "title": "", "image": "", "url": "" }
  ]
}

USER QUESTION:
"${question}"
`;

    /* ─────────────────────────────────────────────── */
    /* 🧠 RESPONSE CACHE */
    /* ─────────────────────────────────────────────── */

    const cacheKey = normalizeQuestion(question);
    const cachedResponse = getCachedResponse(cacheKey);

    if (cachedResponse) {
      return {
        statusCode: 200,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(cachedResponse),
      };
    }

    /* ─────────────────────────────────────────────── */
    /* 6️⃣ AI CALL */
    /* ─────────────────────────────────────────────── */
    const aiResult = await model.generateContent(prompt);
    const aiText = aiResult.response.text();
    const aiData = JSON.parse(aiText);

    /* ─────────────────────────────────────────────── */
    /* 7️⃣ AFFILIATE INJECTION */
    /* ─────────────────────────────────────────────── */
    let answerHtml = aiData.answer_html || "";

    answerHtml = answerHtml
      .replaceAll(
        "{{AFF_FLIGHTS}}",
        `<a class="ai-link" href="${AFFILIATES.flights}" target="_blank" rel="noopener">flights</a>`,
      )
      .replaceAll(
        "{{AFF_HOTELS}}",
        `<a class="ai-link" href="${AFFILIATES.hotels}" target="_blank" rel="noopener">luxury hotels</a>`,
      )
      .replaceAll(
        "{{AFF_TOURS}}",
        `<a class="ai-link" href="${AFFILIATES.tours}" target="_blank" rel="noopener">private tours</a>`,
      )
      .replaceAll(
        "{{AFF_TRANSFERS}}",
        `<a class="ai-link" href="${AFFILIATES.transfers}" target="_blank" rel="noopener">airport transfers</a>`,
      )
      .replaceAll(
        "{{AFF_JETS}}",
        `<a class="ai-link" href="${AFFILIATES.jets}" target="_blank" rel="noopener">private jet charters</a>`,
      );

    /* ─────────────────────────────────────────────── */
    /* 8️⃣ YOUTUBE SEARCH */
    /* ─────────────────────────────────────────────── */
    let video = null;

    if (aiData.video_query) {
      const ytRes = await fetch(
        "https://www.googleapis.com/youtube/v3/search?" +
          new URLSearchParams({
            key: YOUTUBE_API_KEY,
            channelId: YOUTUBE_CHANNEL_ID,
            q: aiData.video_query,
            part: "snippet",
            maxResults: 1,
            type: "video",
            safeSearch: "strict",
          }),
      );

      const yt = await ytRes.json();

      if (yt.items && yt.items.length > 0) {
        video = {
          videoId: yt.items[0].id.videoId,
          title: yt.items[0].snippet.title,
        };
      }
    }

    /* ─────────────────────────────────────────────── */
    /* 9️⃣ RESPONSE */
    /* ─────────────────────────────────────────────── */
    const finalResponse = {
      video,
      answer_html: answerHtml,
      related_guides: aiData.related_guides || [],
    };

    // Save to cache
    setCachedResponse(cacheKey, finalResponse);

    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(finalResponse),
    };
  } catch (error) {
    console.error("AI ERROR:", error);

    return {
      statusCode: 500,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        error: "The AI service is temporarily unavailable. Please try again.",
      }),
    };
  }
};
